name: Build and Upload Book Assets

on:
  push:
    tags:
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]'      # YYYY.MM.DD
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9].[0-9]' # YYYY.MM.DD.N
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9]'                 # YYYY.M.D
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9].[0-9]'           # YYYY.M.D.N
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9]'            # YYYY.MM.D
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9].[0-9]'      # YYYY.MM.D.N
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9][0-9]'            # YYYY.M.DD
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9][0-9].[0-9]'      # YYYY.M.DD.N
  pull_request:
    branches:
      - main  # Only run on PRs to main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only need to read code

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache Task binary
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: cache-task
        with:
          path: /usr/local/bin/task
          key: ${{ runner.os }}-task-binary

      - name: Install Task
        if: steps.cache-task.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install Typst
        uses: typst-community/setup-typst@13c527d2e8ac7863a24510c4043ad28fd47a5606 # v4.1.0
        with:
          typst-version: 'latest'
          cache-dependency-path: '' # Enable caching

      - name: Install Rust for typlite
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo registry
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-typlite
          restore-keys: |
            ${{ runner.os }}-cargo-typlite

      - name: Install typlite
        run: |
          # Check if typlite is already cached
          if ! command -v typlite &> /dev/null; then
            cargo install --git https://github.com/Myriad-Dreamin/tinymist.git typlite
          else
            echo "typlite already installed from cache"
          fi

      - name: Cache APT packages
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: cache-apt
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-pandoc

      - name: Install pandoc
        run: |
          if ! command -v pandoc &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y pandoc
          else
            echo "pandoc already installed"
          fi

      - name: Build all formats
        run: |
          task all

      - name: Upload book artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: windsor-book${{ startsWith(github.ref, 'refs/tags/') && format('-{0}', github.ref_name) || '' }}
          path: dist/
          retention-days: ${{ startsWith(github.ref, 'refs/tags/') && 0 || 30 }}
