name: Build and Upload Book Assets

on:
  push:
    tags:
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]'      # YYYY.MM.DD
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9].[0-9]' # YYYY.MM.DD.N
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9]'                 # YYYY.M.D
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9].[0-9]'           # YYYY.M.D.N
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9]'            # YYYY.MM.D
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9].[0-9]'      # YYYY.MM.D.N
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9][0-9]'            # YYYY.M.DD
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9][0-9].[0-9]'      # YYYY.M.DD.N
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      tag_name:
        description: 'Tag name to build and release'
        required: true
        type: string

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.tag_name && format('refs/tags/{0}', inputs.tag_name) || github.ref }}
          fetch-depth: 0  # Fetch full history including all tags

      - name: Cache Task binary
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: cache-task
        with:
          path: /usr/local/bin/task
          key: ${{ runner.os }}-task-binary

      - name: Install Task
        if: steps.cache-task.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install Typst
        uses: typst-community/setup-typst@13c527d2e8ac7863a24510c4043ad28fd47a5606 # v4.1.0
        with:
          typst-version: 'latest'
          cache-dependency-path: '' # Enable caching

      - name: Install Rust for typlite
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo registry
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-typlite
          restore-keys: |
            ${{ runner.os }}-cargo-typlite

      - name: Install typlite
        run: |
          # Check if typlite is already cached
          if ! command -v typlite &> /dev/null; then
            cargo install --git https://github.com/Myriad-Dreamin/tinymist.git typlite
          else
            echo "typlite already installed from cache"
          fi

      - name: Cache APT packages
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: cache-apt
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-pandoc-diagrams-v2

      - name: Install pandoc and diagram dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-pictures \
            imagemagick \
            librsvg2-bin \
            ghostscript

          # Verify installations
          echo "✅ Installed packages:"
          pandoc --version | head -1
          pdflatex --version | head -1
          convert --version | head -1
          rsvg-convert --version | head -1
          gs --version | head -1

      - name: Build all formats
        run: |
          task all

      - name: Rename files for release
        if: startsWith(github.ref, 'refs/tags/') || inputs.tag_name
        run: |
          TAG_NAME="${{ inputs.tag_name || github.ref_name }}"
          cd dist/

          # Rename files to include version
          mv unified-cloud-native-development-with-windsor.pdf windsor-book-${TAG_NAME}.pdf
          mv unified-cloud-native-development-with-windsor.epub windsor-book-${TAG_NAME}.epub
          mv unified-cloud-native-development-with-windsor.html windsor-book-${TAG_NAME}.html
          mv unified-cloud-native-development-with-windsor.md windsor-book-${TAG_NAME}.md

      - name: Upload book artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: windsor-book${{ (startsWith(github.ref, 'refs/tags/') && format('-{0}', github.ref_name)) || (inputs.tag_name && format('-{0}', inputs.tag_name)) || '' }}
          path: dist/
          retention-days: ${{ (startsWith(github.ref, 'refs/tags/') || inputs.tag_name) && 0 || 30 }}

      - name: Generate changelog
        id: changelog
        if: startsWith(github.ref, 'refs/tags/') || inputs.tag_name
        run: |
          # Get all tags sorted by version
          ALL_TAGS=$(git tag --sort=-version:refname)
          CURRENT_TAG="${{ inputs.tag_name || github.ref_name }}"

          echo "🔍 Debug: Current tag: $CURRENT_TAG"
          echo "🔍 Debug: All tags: $ALL_TAGS"

          # Find the previous tag (skip the current one)
          LAST_TAG=""
          FOUND_CURRENT=false
          for tag in $ALL_TAGS; do
            if [ "$tag" = "$CURRENT_TAG" ]; then
              FOUND_CURRENT=true
              continue
            fi
            if [ "$FOUND_CURRENT" = true ]; then
              LAST_TAG="$tag"
              break
            fi
          done

          echo "🔍 Debug: Previous tag: $LAST_TAG"

          if [ -z "$LAST_TAG" ]; then
            echo "## First Release" > changelog.md
            echo "" >> changelog.md
            echo "Initial release of the Windsor CLI book." >> changelog.md
          else
            echo "## Changes since $LAST_TAG" > changelog.md
            echo "" >> changelog.md

            # Get commits since last tag, format as changelog
            echo "🔍 Debug: Running git log $LAST_TAG..$CURRENT_TAG"
            git log --oneline --pretty=format:"- %s" $LAST_TAG..$CURRENT_TAG >> changelog.md

            # If no commits, add a note
            if [ ! -s changelog.md ] || [ "$(wc -l < changelog.md)" -le 2 ]; then
              echo "- Documentation updates and improvements" >> changelog.md
            fi
          fi

          echo "🔍 Debug: Generated changelog:"
          cat changelog.md

          # Set output for use in release using base64 encoding to avoid delimiter issues
          CHANGELOG_CONTENT=$(cat changelog.md | base64 -w 0)
          echo "changelog_b64=$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT

      - name: Decode changelog
        id: decode_changelog
        if: startsWith(github.ref, 'refs/tags/') || inputs.tag_name
        run: |
          echo "${{ steps.changelog.outputs.changelog_b64 }}" | base64 -d > decoded_changelog.md
          echo "changelog<<CHANGELOG_DELIMITER" >> $GITHUB_OUTPUT
          cat decoded_changelog.md >> $GITHUB_OUTPUT
          echo "CHANGELOG_DELIMITER" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        if: startsWith(github.ref, 'refs/tags/') || inputs.tag_name
        with:
          tag_name: ${{ inputs.tag_name || github.ref_name }}
          name: "Windsor CLI Book ${{ inputs.tag_name || github.ref_name }}"
          body: |
            # Windsor CLI Book Release ${{ inputs.tag_name || github.ref_name }}

            **Published:** ${{ inputs.tag_name || github.ref_name }}

            ## 📚 Available Formats

            - **PDF**: Professional print-ready format with full typography
            - **EPUB**: E-reader compatible format
            - **HTML**: Standalone web page with navigation (includes CSS)
            - **Markdown**: Raw documentation format

            ## 📝 Changelog

            ${{ steps.decode_changelog.outputs.changelog }}

            ---

            *This release covers Windsor CLI development practices and infrastructure orchestration.*
          files: |
            dist/windsor-book-${{ inputs.tag_name || github.ref_name }}.pdf
            dist/windsor-book-${{ inputs.tag_name || github.ref_name }}.epub
            dist/windsor-book-${{ inputs.tag_name || github.ref_name }}.html
            dist/windsor-book-${{ inputs.tag_name || github.ref_name }}.md
            dist/book.css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
