name: Build and Upload Book Assets

on:
  push:
    tags:
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]'      # YYYY.MM.DD
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9].[0-9]' # YYYY.MM.DD.N
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9]'                 # YYYY.M.D
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9].[0-9]'           # YYYY.M.D.N
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9]'            # YYYY.MM.D
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9].[0-9]'      # YYYY.MM.D.N
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9][0-9]'            # YYYY.M.DD
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9][0-9].[0-9]'      # YYYY.M.DD.N
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      tag_name:
        description: 'Tag name to build and release'
        required: true
        type: string

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.tag_name && format('refs/tags/{0}', inputs.tag_name) || github.ref }}

      - name: Cache Task binary
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: cache-task
        with:
          path: /usr/local/bin/task
          key: ${{ runner.os }}-task-binary

      - name: Install Task
        if: steps.cache-task.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install Typst
        uses: typst-community/setup-typst@13c527d2e8ac7863a24510c4043ad28fd47a5606 # v4.1.0
        with:
          typst-version: 'latest'
          cache-dependency-path: '' # Enable caching

      - name: Install Rust for typlite
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo registry
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-typlite
          restore-keys: |
            ${{ runner.os }}-cargo-typlite

      - name: Install typlite
        run: |
          # Check if typlite is already cached
          if ! command -v typlite &> /dev/null; then
            cargo install --git https://github.com/Myriad-Dreamin/tinymist.git typlite
          else
            echo "typlite already installed from cache"
          fi

      - name: Cache APT packages
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: cache-apt
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-pandoc

      - name: Install pandoc
        run: |
          if ! command -v pandoc &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y pandoc
          else
            echo "pandoc already installed"
          fi

      - name: Build all formats
        run: |
          task all

      - name: Upload book artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: windsor-book${{ (startsWith(github.ref, 'refs/tags/') && format('-{0}', github.ref_name)) || (inputs.tag_name && format('-{0}', inputs.tag_name)) || '' }}
          path: dist/
          retention-days: ${{ (startsWith(github.ref, 'refs/tags/') || inputs.tag_name) && 0 || 30 }}

      - name: Generate changelog
        id: changelog
        if: startsWith(github.ref, 'refs/tags/') || inputs.tag_name
        run: |
          # Get the last release tag
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")

          if [ -z "$LAST_TAG" ]; then
            echo "## First Release" > changelog.md
            echo "" >> changelog.md
            echo "Initial release of the Windsor CLI book." >> changelog.md
          else
            echo "## Changes since $LAST_TAG" > changelog.md
            echo "" >> changelog.md

            # Get commits since last tag, format as changelog
            git log --oneline --pretty=format:"- %s" $LAST_TAG..HEAD >> changelog.md

            # If no commits, add a note
            if [ ! -s changelog.md ]; then
              echo "- Documentation updates and improvements" >> changelog.md
            fi
          fi

          # Set output for use in release
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          cat changelog.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.3.2
        if: startsWith(github.ref, 'refs/tags/') || inputs.tag_name
        with:
          tag_name: ${{ inputs.tag_name || github.ref_name }}
          name: "Windsor CLI Book ${{ inputs.tag_name || github.ref_name }}"
          body: |
            # Windsor CLI Book Release ${{ inputs.tag_name || github.ref_name }}

            **Published:** ${{ inputs.tag_name || github.ref_name }}

            ## 📚 Available Formats

            - **PDF**: Professional print-ready format with full typography
            - **EPUB**: E-reader compatible format
            - **HTML**: Standalone web page with navigation (includes CSS)
            - **Markdown**: Raw documentation format

            ## 📝 Changelog

            ${{ steps.changelog.outputs.changelog }}

            ---

            *This release covers Windsor CLI development practices and infrastructure orchestration.*
          files: |
            dist/unified-cloud-native-development-with-windsor.pdf
            dist/unified-cloud-native-development-with-windsor.epub
            dist/unified-cloud-native-development-with-windsor.html
            dist/unified-cloud-native-development-with-windsor.md
            dist/book.css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
