name: Build and Upload Book Assets

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to upload release assets

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install Typst
        uses: typst-community/setup-typst@13c527d2e8ac7863a24510c4043ad28fd47a5606 # v4.1.0
        with:
          typst-version: 'latest'

      - name: Install Rust for typlite
        uses: dtolnay/rust-toolchain@stable

      - name: Install typlite
        run: |
          cargo install --git https://github.com/Myriad-Dreamin/tinymist.git typlite

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build all formats
        run: |
          task all

      - name: Upload book artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: book-formats
          path: |
            dist/unified-cloud-native-development-with-windsor.pdf
            dist/unified-cloud-native-development-with-windsor.epub
            dist/unified-cloud-native-development-with-windsor.html
            dist/unified-cloud-native-development-with-windsor.md
          retention-days: ${{ startsWith(github.ref, 'refs/tags/v') && 0 || 30 }}
