name: Build and Upload Book Assets

on:
  push:
    tags:
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]'      # YYYY.MM.DD
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9].[0-9]' # YYYY.MM.DD.N
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9]'                 # YYYY.M.D
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9].[0-9]'           # YYYY.M.D.N
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9]'            # YYYY.MM.D
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9].[0-9]'      # YYYY.MM.D.N
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9][0-9]'            # YYYY.M.DD
      - '[0-9][0-9][0-9][0-9].[0-9].[0-9][0-9].[0-9]'      # YYYY.M.DD.N
  pull_request:
    branches:
      - main  # Only run on PRs to main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only need to read code

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install Typst
        uses: typst-community/setup-typst@13c527d2e8ac7863a24510c4043ad28fd47a5606 # v4.1.0
        with:
          typst-version: 'latest'

      - name: Install Rust for typlite
        uses: dtolnay/rust-toolchain@stable

      - name: Install typlite
        run: |
          cargo install --git https://github.com/Myriad-Dreamin/tinymist.git typlite

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build all formats
        run: |
          task all

      - name: Upload PDF
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: windsor-book${{ startsWith(github.ref, 'refs/tags/') && format('-{0}', github.ref_name) || '' }}.pdf
          path: dist/unified-cloud-native-development-with-windsor.pdf
          retention-days: ${{ startsWith(github.ref, 'refs/tags/') && 0 || 30 }}
          compression-level: 0

      - name: Upload EPUB
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: windsor-book${{ startsWith(github.ref, 'refs/tags/') && format('-{0}', github.ref_name) || '' }}.epub
          path: dist/unified-cloud-native-development-with-windsor.epub
          retention-days: ${{ startsWith(github.ref, 'refs/tags/') && 0 || 30 }}
          compression-level: 0

      - name: Upload HTML with CSS
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: windsor-book${{ startsWith(github.ref, 'refs/tags/') && format('-{0}', github.ref_name) || '' }}-html
          path: |
            dist/unified-cloud-native-development-with-windsor.html
            dist/book.css
          retention-days: ${{ startsWith(github.ref, 'refs/tags/') && 0 || 30 }}

      - name: Upload Markdown
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: windsor-book${{ startsWith(github.ref, 'refs/tags/') && format('-{0}', github.ref_name) || '' }}.md
          path: dist/unified-cloud-native-development-with-windsor.md
          retention-days: ${{ startsWith(github.ref, 'refs/tags/') && 0 || 30 }}
          compression-level: 0
