name: Create Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Generate CalVer version
        id: calver
        run: |
          # Generate CalVer version (YYYY.MM.DD format)
          VERSION=$(date +"%Y.%m.%d")

          # Check if tag already exists and increment if needed
          COUNTER=0
          FINAL_VERSION="$VERSION"

          while git rev-parse "refs/tags/$FINAL_VERSION" >/dev/null 2>&1; do
            COUNTER=$((COUNTER + 1))
            FINAL_VERSION="$VERSION.$COUNTER"
          done

          echo "Generated version: $FINAL_VERSION"
          echo "version=$FINAL_VERSION" >> $GITHUB_OUTPUT

          # Create the tag
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$FINAL_VERSION" -m "Release $FINAL_VERSION"
          git push origin "$FINAL_VERSION"

      - name: Generate changelog
        id: changelog
        run: |
          # Get the last release tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

          if [ -z "$LAST_TAG" ]; then
            echo "## First Release" > changelog.md
            echo "" >> changelog.md
            echo "Initial release of the Windsor CLI book." >> changelog.md
          else
            echo "## Changes since $LAST_TAG" > changelog.md
            echo "" >> changelog.md

            # Get commits since last tag, format as changelog
            git log --oneline --pretty=format:"- %s" $LAST_TAG..HEAD >> changelog.md

            # If no commits, add a note
            if [ ! -s changelog.md ]; then
              echo "- Documentation updates and improvements" >> changelog.md
            fi
          fi

          # Set output for use in release
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          cat changelog.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.3.2
        with:
          tag_name: ${{ steps.calver.outputs.version }}
          name: "Windsor CLI Book ${{ steps.calver.outputs.version }}"
          body: |
            # Windsor CLI Book Release ${{ steps.calver.outputs.version }}

            **Published:** ${{ steps.calver.outputs.version }}

            ## 📚 Available Formats

            Book artifacts are available in the [GitHub Actions artifacts](https://github.com/${{ github.repository }}/actions) from the build that triggered this release.

            - **PDF**: Professional print-ready format with full typography
            - **EPUB**: E-reader compatible format
            - **HTML**: Standalone web page with navigation
            - **Markdown**: Raw documentation format

            ## 📝 Changelog

            ${{ steps.changelog.outputs.changelog }}

            ---

            *This release covers Windsor CLI development practices and infrastructure orchestration.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
