name: Create Release

on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.calver.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Generate CalVer version and create tag
        id: calver
        run: |
          # Generate CalVer version (YYYY.MM.DD format)
          VERSION=$(date +"%Y.%-m.%-d")

          # Check if tag already exists and increment if needed
          COUNTER=0
          FINAL_VERSION="$VERSION"

          while git rev-parse "refs/tags/$FINAL_VERSION" >/dev/null 2>&1; do
            COUNTER=$((COUNTER + 1))
            FINAL_VERSION="$VERSION.$COUNTER"
          done

          echo "Generated version: $FINAL_VERSION"
          echo "version=$FINAL_VERSION" >> $GITHUB_OUTPUT

          # Create and push the tag
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$FINAL_VERSION" -m "Release $FINAL_VERSION"
          git push origin "$FINAL_VERSION"

          echo "Created and pushed tag: $FINAL_VERSION"

  build-and-release:
    needs: create-tag
    uses: ./.github/workflows/publish.yml
    with:
      tag_name: ${{ needs.create-tag.outputs.version }}
    permissions:
      contents: write
